### ISSUE TITLE
Allow '' or empty first argument to trigger

### ISSUE THREAD

**Issue by HaleTom** [CodesOfRishi/smartcd#10]
I find it much easier to type `''` than `--`.  

Also, `--` has a valid meaning eg, `cd -P -e -- -P`.

In this example, `P` and `e` are arguments to `cd` (please pass these through!) whereas the `--` says that what follows, ie `-P` is not an argument to `cd` itself, but rather the directory to change to. (Useful if you have directory names starting with a `-`)

**Comment by CodesOfRishi** [comment]
You can export `SMARTCD_HIST_OPT` with your desired option instead of `--`.
Check [Configurations](https://github.com/CodesOfRishi/smartcd#configurations).

**Comment by HaleTom** [comment]
When I do:

```
SMARTCD_HIST_OPT=''
cd ''
```
I don't get completions. This could be related to quoting in #9, but more likely related to the tricksy way to check if a variable is "set" (as this issue requires) vs the easier "set and contains a value". 

https://stackoverflow.com/a/13864829/5353461

**Comment by CodesOfRishi** [comment]
Try `export SMARTCD_HIST_OPT="''"`

To get the `fzf` window, you may need to run `cd \'\'`, i.e., provide backslashes otherwise the shell may interpret it as quotes.

**Comment by HaleTom** [comment]
I actually want the argument to be the null string, ie it could equally be represented by `''` or `""`.  It just so happens that `''` is easier to type than `""` :)

I think you're after this:
https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html#:~:text=Omitting%20the%20colon%20results%20in%20a%20test%20only%20for%20a%20parameter%20that%20is%20unset.

```
export SMARTCD_HIST_OPT=${SMARTCD_HIST_OPT:-"--"} 
```
to:
```
export SMARTCD_HIST_OPT=${SMARTCD_HIST_OPT-"--"} 
```

**Comment by CodesOfRishi** [comment]
I get it! Looking into it, thanks!

**Comment by HaleTom** [comment]
Thanks for fixing this!  Now my pinky finger can get fat and lazy 😂
