### ISSUE TITLE
Breaks zsh tab completion 

### ISSUE THREAD

**Issue by HaleTom** [CodesOfRishi/smartcd#11]
Without the plugin, if I type `cd ` and press <kbd>TAB</kbd> I get a list of only directories.

With the plugin, both files and directories are listed.

`.zshrc` config required:
```
autoload -Uz compinit && compinit
```

**Comment by HaleTom** [comment]
```
if [[ -n $ZSH_VERSION ]]; then
    # Enable Zsh completions as for builtin cd
    compdef __smartcd__=cd
fi
```

**Comment by HaleTom** [comment]
Ah, you'd also want to check that compdef is actually a function. It isn't until after compinit is run.

**Comment by CodesOfRishi** [comment]
> ```
> if [[ -n $ZSH_VERSION ]]; then
>     # Enable Zsh completions as for builtin cd
>     compdef __smartcd__=cd
> fi
> ```

Is this working for you?

**Comment by CodesOfRishi** [comment]
Thanks again!!

**Comment by HaleTom** [comment]
Cheers!

**Comment by HaleTom** [comment]
It would be great if this worked straight out of the box with less config:

```
[[ -n $ZSH_VERSION ]] && typeset -f compdef > /dev/null && compdef __smartcd__=cd
```
This would be ignored for `bash`, or if `compinit` hadn't yet been called.

**Comment by CodesOfRishi** [comment]
Yep, right! I will implement this!!
