### ISSUE TITLE
Changing to permission denied directory

### ISSUE THREAD

**Issue by HaleTom** [CodesOfRishi/smartcd#14]
```
% mkdir -m000 noperms     
```

Standard behaviour:

```
% builtin cd noperms 
cd: permission denied: noperms
% 
```

With SmartCd, I get a directory search.

```
% cd noperms 
No directory found or selected!
```

If the specified diretory exists, can it fail just like the builtin `cd`?

**Comment by CodesOfRishi** [comment]
Can you provide more info like which version of SmartCd you're using, where exactly (the directory location) you created the `noperms` directory & from which directory location you're trying to `cd` into it?

**Comment by CodesOfRishi** [comment]
Thanks agn for reporting!

**Comment by HaleTom** [comment]
I'd suggest a more generic approach than just checking for one possible error messsage:
```
builtin cd ${path_argument}
if [ $? -ne 0 ]; then
  # cd failed for whatever reason
fi
# happy path continues...
```

**Comment by CodesOfRishi** [comment]
Yep. I'm aware of it. Will be looking into it. Thanks!
