### ISSUE TITLE
Allow setting search root

### ISSUE THREAD

**Issue by HaleTom** [CodesOfRishi/smartcd#15]
Often in a deep directory, I want to be able to cd and search to anywhere below `$HOME`.

I'd like to be able to do:

```
alias hcd='f() { SMARTCD_ROOT=$HOME; cd "$@"; unset SMARTCD_HOME; };f'
```

Would you consider a `SMARTCD_ROOT` variable from which the listing is generated?  I'd suggest a subshell for the generation to allow for user `^C` or permission denied on the target directory.

**Comment by CodesOfRishi** [comment]
You can now try either `-b` or `--base` option to search and traverse into `$HOME`.

**Comment by HaleTom** [comment]
Thank you! 💙
