### ISSUE TITLE
[BUG] `whereis -b` not supported on macOS

### ISSUE THREAD

**Issue by HaleTom** [CodesOfRishi/smartcd#19]
**Issue observed in the following shell(s):**
- [ ] Bash
- [x] Zsh

**Describe the bug**
Upon shell startup:

```
whereis: illegal option -- b
usage: whereis program [...]
Can't use SmartCd: fzf not found !
```

I suggest you do:

```
is_cmd () {
        command -v "$1" >&/dev/null
}
```
and then:

```
	if is_cmd fdfind; then
```

**Expected behaviour**
No error

**Comment by CodesOfRishi** [comment]
I think this can fail if the expected executable name that I am passing to `command -v` is not an installed executable, but an alias!

**Comment by CodesOfRishi** [comment]
I'm not sure, but I think I should go with the `hash` command instead.

**Comment by HaleTom** [comment]
You're right on the aliases!

To avoid the "determine and remember" overhead of re-hashing, when I want to get a binary's path, I use:

```
bin_path () {
        if [[ -n ${ZSH_VERSION:-} ]]; then
                builtin whence -cp "$1" 2> /dev/null
        else
                builtin type -P "$1"
        fi
}
```
Tweaking for silent, return value only:
```
has_bin () {
        if [[ -n ${ZSH_VERSION:-} ]]; then
                builtin whence -cp "$1" >& /dev/null
        else
                builtin type -P "$1"  >& /dev/null
        fi
}
```

**Comment by CodesOfRishi** [comment]
The concern regarding re-hashing is moved to another issue #22.
