### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by drewauff** [CodesOfRishi/smartcd#2]
```
whereis: illegal option -- b
usage: whereis program [...]
whereis: illegal option -- b
usage: whereis program [...]
Can't use SmartCd: fzf not found !
whereis: illegal option -- b
usage: whereis program [...]
Can't use SmartCd: fd not found !
```

**Comment by drewauff** [comment]
ok got it loaded, but cant get it to work..nothing happens or shows with cd or cd --?

**Comment by CodesOfRishi** [comment]
First, you will need both [fzf](https://github.com/junegunn/fzf) and [fd](https://github.com/sharkdp/fd).
Secondly, traverse a few directories so that SmartCd can log them. Then try again with `cd -- [string]`.
Lastly, regarding other features, they should work straight away.

**Comment by drewauff** [comment]
I am a long time user of fzf and fd among a crap tonne of other things..

Oh I see, did not take into account the dir. traverse logging.

Ok thank you, will give a shot!

**Comment by CodesOfRishi** [comment]
Just don't forget to update on the issue plz!
