### ISSUE TITLE
[BUG] Variable namespace pollution

### ISSUE THREAD

**Issue by HaleTom** [CodesOfRishi/smartcd#20]
**Are you using the latest version?**
4.0.0

**The issue is with the following feature(s):**
- [ ] Traversal to root of a git repository.
- [ ] Search & traverse w.r.t. to a base directory.
- [ ] Search & traverse recently visited directories.
- [ ] Sub-directory search & traversal.
- [ ] Parent-directory search & traversal.
- [ ] Piping.
- [ ] Cleaning of log file.
- [ ] Installation.
- [ ] Dependencies/Requirements.
- [ ] Configurations.
- [ ] Documentation.
- [x] Other(s)

**Issue observed in the following shell(s):**
- [x] Bash
- [x] Zsh

**Describe the bug**
I get unwanted and unneeded extra variables after sourcing this.

Eg `_feats`.  (which may be better named singular anyway).

**To Reproduce**
Steps to reproduce the behaviour:
1. `( set -o posix ; set ) > before`
2. Source plugin
2. `( set -o posix ; set ) > after`
3. `diff before after`

**Expected behaviour**
Minimum set of required variables are added, and only exported if needed

**Comment by CodesOfRishi** [comment]
Nice catch! Thanks!
