### ISSUE TITLE
If possible, avoid using `hash` as it hashes binary's path

### ISSUE THREAD

**Issue by CodesOfRishi** [CodesOfRishi/smartcd#22]
**Are you using the latest version?**
v4.0.0

**The issue is with the following feature(s):**
- [ ] Traversal to root of a git repository.
- [ ] Search & traverse w.r.t. to a base directory.
- [ ] Search & traverse recently visited directories.
- [ ] Sub-directory search & traversal.
- [ ] Parent-directory search & traversal.
- [ ] Piping.
- [ ] Cleaning of log file.
- [ ] Installation.
- [ ] Dependencies/Requirements.
- [ ] Configurations.
- [ ] Documentation.
- [x] Other(s)

**Issue observed in the following shell(s):**
- [x] Bash
- [x] Zsh

**Describe the bug**
SmartCd is using `hash` command to validate whether an executable exist or not.
`hash` command hashes the searched path for faster lookup next time when it's used again. Hashing is really not necessary here.

**Additional context**
Possible alternatives:
- `whence` command in `zsh`. (run `man zshbuiltins` & search `whence`)
- `type` command in `bash`. (run `help type`)

Possible solution:
```bash
path_search() {
	local _executable=$1
	if ps -p $$ | grep -i --quiet 'zsh$'; then
		whence -p "${_executable}" &> /dev/null
	elif ps -p $$ | grep -i --quiet 'bash$'; then
		type -P "${_executable}" &> /dev/null
	else 
		printf '%s\n' "Shell doesn't seems to be either Base or Zsh" 1>&2
		return 1
	fi
}
```

**Comment by HaleTom** [comment]
Why do you fork two processes (ps and grep) when you could look up (e.g.) $BASH_VERSION or $SHELL ?

**Comment by CodesOfRishi** [comment]
Coz for now I'm not sure if it's reliable! Or is it??

**Comment by CodesOfRishi** [comment]
For example, if you launch another shell as a subprocess, the value of `$SHELL` won't change!
I am not sure with the other one (`$BASH_VERSION`)!
