### ISSUE TITLE
Add zinit installation instructions

### ISSUE THREAD

**Issue by HaleTom** [CodesOfRishi/smartcd#7]
### [Zinit](https://github.com/zdharma-continuum/zinit)

```
zinit ice wait  # For faster prompt loading
zinit snippet 'https://raw.githubusercontent.com/CodesOfRishi/smartcd/main/smartcd.sh'
```

----

For copy paste:

```
### [Zinit](https://github.com/zdharma-continuum/zinit)
```

**Comment by HaleTom** [comment]
An improvement on this:

```
zinit ice wait depth"1"
zinit light 'CodesOfRishi/smartcd'
```

The previous `snippet` line should be removed in favour of these.

This will shallow clone the repository and allow the user to keep their own personal commits will be merged at the next pull.

**Comment by CodesOfRishi** [comment]
Installation through shallow clone using Zinit, so as for the user to make personal commits & merge them with others, I should leave these parts for the users to decide and research about since I don't think it's very specific to SmartCd.
