### ISSUE TITLE
generate_recent_dir_log:4: file exists: /tmp/tmp.CZWymagmxT

### ISSUE THREAD

**Issue by HaleTom** [CodesOfRishi/smartcd#8]
In generate_recent_dir_log (), please change:

```
printf '%s\n' "${PWD}" > ${tmp_log}
```
to
```
printf '%s\n' "${PWD}" >> ${tmp_log}
```

Necessary to work with bash's [`noclobber`](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html#:~:text=on%20by%20default.-,%2DC,-Prevent%20output%20redirection)

**Comment by HaleTom** [comment]
Likewise `>|`:
```
		awk '!seen[$0]++' ${tmp_log} >| ${recent_dir_log} # remove duplicates
```

**Comment by CodesOfRishi** [comment]
References:
[How to protect files from overwriting with noclobber in bash](https://howto.lintel.in/protect-files-overwriting-noclobber-bash/)
[Bash: What does ">|" do?](https://unix.stackexchange.com/questions/45201/bash-what-does-do)

**Comment by CodesOfRishi** [comment]
Thanks!

**Comment by HaleTom** [comment]
Thanks for fixing so quickly! :smiley:
