### ISSUE TITLE
Fix shellcheck error / warnings

### ISSUE THREAD

**Issue by HaleTom** [CodesOfRishi/smartcd#9]
Please run shellcheck against this -- there are many warnings and an error:
```
 validate_parameters $@ ${piped_value}
```

Should be: `"$@"`.

**Comment by CodesOfRishi** [comment]
Thanks!

**Comment by HaleTom** [comment]
Please consider re-opening - there are many more issues than the one I pointed out.
https://github.com/koalaman/shellcheck

**Comment by HaleTom** [comment]
I'd highly recommend adding `shellcheck` to your list of linters to prevent ongoing issues, but it's also available for copy-paste usage [online](https://www.shellcheck.net/).

**Comment by CodesOfRishi** [comment]
Yes, I will try to fix other warning/infos stated by `shellcheck` separately.
The one (& only) error it showed & you mentioned, I have fixed it.

**Comment by HaleTom** [comment]
Thanks for getting the warnings, too!
